// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package golang_framework

import (
	"go_framework/internal/adapters/gormadapter"
	"go_framework/internal/app"
	"go_framework/internal/app/services"
	"go_framework/internal/pkg/configs"
	"go_framework/internal/pkg/database"
)

// Injectors from wire.go:

func InitializeServer() *app.Application {
	configsConfigs := configs.NewServerConfig()
	db := database.NewGormDb(configsConfigs)
	postRepo := gormadapter.NewGormPostRepo(db)
	postServices := services.NewPostService(postRepo)
	trxHandler := gormadapter.NewTransactionHandler(db)
	application := app.NewApplication(configsConfigs, postServices, trxHandler)
	return application
}
