// Package ports provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package ports

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for PostCreateStatus.
const (
	N1 PostCreateStatus = 1
	N2 PostCreateStatus = 2
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// PostCreate defines model for PostCreate.
type PostCreate struct {
	Content string             `json:"content"`
	ShowAt  openapi_types.Date `json:"showAt"`
	Status  PostCreateStatus   `json:"status"`
	Title   string             `json:"title"`
	UserNo  string             `json:"user_no"`
}

// PostCreateStatus defines model for PostCreate.Status.
type PostCreateStatus int

// PostCreateJSONRequestBody defines body for PostCreate for application/json ContentType.
type PostCreateJSONRequestBody = PostCreate
