// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"go_framework/internal/adapters/gormRepo"
	"go_framework/internal/app/services"
	"go_framework/internal/pkg/database"
)

// Injectors from wire.go:

func InitializeServer() Application {
	db := database.NewGormDb()
	postRepo := gormRepo.NewGormPostRepo(db)
	postServices := services.NewPostService(postRepo)
	application := NewApplication(postServices)
	return application
}
